### ISSUE TITLE
Update phpunit/php-timer dependency to ^1.0|^2.0|^3.0|^4.0|^5.0

### ISSUE THREAD

**Issue by rohsyl** [antonioribeiro/health#204]
Hello,

I'm using your package in my project and have the following error when doing the `composer require`

![image](https://user-images.githubusercontent.com/18440665/93103428-e67d4a80-f6ac-11ea-93c5-52eb5c509d71.png)

Last release v0.10.3 is using the followings:
`"phpunit/php-timer": "^1.0|^2.0",`

I saw that you already updateded it in master.

Master :
`"phpunit/php-timer": "^1.0|^2.0|^3.0|^4.0|^5.0",`

Could you release that new version with the `phpunit/php-timer `dependency updated ?

Thanks a lot !

**Comment by truesteps** [comment]
Hey! I would like to bump this issue

**Comment by truesteps** [comment]
@rohsyl after a little bit of investigation, it seems that bumping the version isn't enough. I'm not sure whether you noticed, but in never versions of laravel, with never versions of php timer, the runtime of the health check always returns null making saving records into DB impossible, since it will result in the failure of all health checks. If you need to use the master release, just pust `dev-master` into the version in `composer.json` and composer will check out the master branch. But the maintainer of this package did well, not to release it, since it would break already existing implementations. Good work maintainer!

**Comment by rohsyl** [comment]
Thanks for your comment mate.

I already pulled the `dev-master` version to wait until the maintainer of the package fix it all.

**Comment by antonioribeiro** [comment]
Should be fixed now. Version 0.11.0 tagged.
