### ISSUE TITLE
Queue check leaves pile of jobs in queue

### ISSUE THREAD

**Issue by jmauerhan** [antonioribeiro/health#59]
First of all, I love this library, saved me a ton of effort. I am using the Queue checker to ensure that my app is configured correctly to talk to Beanstalk. 

I noticed that now that it's been running, there is a new Queue called "Queue" that has 19k jobs sitting ready. What is the recommended way to handle this, should I set up a worker to clean these out, or just ignore it?

**Comment by NHuebner1983** [comment]
Hi there. I actually freaked out when I saw this as well, thinking HealthPing was pinging a website wondering if my internet was going to go down (haha).

Since I am using Redis, I had to use `redis-cli` then type `FLUSHALL`.

If you're not using Redis, you will probably have a `jobs` table. You can also try the `php artisan queue` commands which might help. Good luck!
